config/routes.rb
Rails.application.routes.draw do

  resources 'uploads', only: [:create, :destroy]

  # root
  root to: 'articles#index'

  # devise
  # devise_for :admins, controllers: {
  # sessions:      'admins/sessions',
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
  # }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  resource :two_factor_auth, only: [:new, :create, :destroy]

  # admins
  # resources :admins, only: [ :index, :create, :edit, :show, :update]

  # get 'admins/:id/password', to: 'admins#password', as: 'admin_password_setting'

  # get 'admins/:id/profile', to: 'admins#profile', as: 'admin_profile'

  # get 'admins/:id/two_factor_authentication', to: 'admins#two_factor_authentication', as: 'admin_two_factor_authentication'

  # users
  resources :users, only: [ :index, :create, :edit, :show, :update] do
    resources :drafts do
      member do
        get 'confirm'
        post 'create_article'
      end
    end
    member do
     get :following, :followers
    end
  end

  get 'users/:id/favorites', to: 'users#favorites', as: 'favorites'

  get 'users/:id/comments', to: 'users#comments', as: 'comments'

  get 'users/:id/followers', to: 'users#followers', as: 'followers'

  get 'users/:id/followings', to: 'users#followings', as: 'followings'

  # get 'users/:id/account', to: 'users#account', as: 'user_account'

  get 'users/:id/password', to: 'users#password', as: 'user_password_setting'

  patch 'users/:id/update_password', to: 'users#update_password', as: 'update_password'

  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'

  get 'users/:id/two_factor_authentication', to: 'users#two_factor_authentication', as: 'user_two_factor_authentication'

  get 'users/:id/confirm_unsubscribe', to: 'users#confirm_unsubscribe', as: 'confirm_unsubscribe'

  patch 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'

  # relationships
  resources :relationships, only: [:create, :destroy]

  # articles
  resources :articles do
    resources :comments, only: [ :index, :create, :show, :update, :destroy]
    # resource :images, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :keeps, only: [:create, :destroy]
    collection do
      post 'confirm'
    end
  end

  get 'user_timeline', to: 'articles#user_timeline', as: 'user_timeline'

  get 'tag_timeline', to: 'articles#tag_timeline', as: 'tag_timeline'

  get 'articles/:id/confirm_edit', to: 'articles#confirm_edit', as: 'confirm_edit'

  # keeps
  resources :keeps, only: [:index]

  # tags
  resources :tags, only: [ :index, :create, :show ] do
    collection do
      post 'add'
    end
  end

  # taggings
  resources :taggings, only: [ :destroy]

  # contacts
  # resources :contacts, only: [ :index, :create, :new, :show, :update]

  # get 'contacts/confirm', to: 'contacts#confirm', as: 'confirm_contact'

  # get 'contacts/sent', to: 'contacts#sent', as: 'sent_contact'

  # terms
  # get 'terms', to: 'terms#index', as: 'terms'

  # help
  # get 'help', to: 'helps#index', as: 'helps'

  # about
  get 'about', to: 'abouts#about', as: 'about'

  # posts
  resources :posts

  # notifications
  resources :notifications

  get 'notifications/link_through'

  patch 'update_notification', to: 'notifications#update_notification', as: "update_notification"

  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	# Association
	has_many :notifications
	belongs_to :article
	belongs_to :user

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	before_action :return_user

  def create
		favorite = current_user.favorites.new(article_id: params[:article_id])
		favorite.save
		add_one_point
		create_notification
		create_post
    flash.now[:flash_message] = "この記事を#{"イイね"}しました"
    @flash_message = flash.now[:flash_message]
  end

  def destroy
		favorite = current_user.favorites.find_by(article_id: params[:article_id])
		favorite.destroy
		subtract_one_point
		destroy_notification
		destroy_post
    flash.now[:flash_message] = "この記事の#{"イイね"}を取り消しました"
    @flash_message = flash.now[:flash_message]
  end





	private

	def return_user
		if user_signed_in?
			@article = Article.find(params[:article_id])
			@user = User.find(@article.user_id)
			return if @article.user_id == current_user.id
		else
			return
		end
	end

  def create_post
    Post.create(
    						user_id: @article.user_id,
    						posted_by_id: current_user.id,
                article_id: @article.id,
                posted_type: "イイね")
  end

	def destroy_post
		post = Post.find_by(
	                  user_id: @article.user_id,
	                  posted_by_id: current_user.id,
	                  article_id: @article.id,
	                  posted_type: "イイね")
		post.destroy
	end

	def create_notification
		Notification.create(
		                  user_id: @article.user_id,
		                  notified_by_id: current_user.id,
		                  article_id: @article.id,
		                  notified_type: "イイね")
	end

	def destroy_notification
		notification = Notification.find_by(
	                  user_id: @article.user_id,
	                  notified_by_id: current_user.id,
	                  article_id: @article.id,
	                  notified_type: "イイね")
		notification.destroy
	end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if article.favorited_by?(current_user) %>

	<%= link_to article_favorites_path(article), style: "text-decoration: none;", method: :delete, id: "favorite-link", remote: true do %>

		<span class="list-group-item list-group-item-action nav-font text-white mb-2" style="background-color: #ffa500;">
			<div class="font-weight-bold d-md-none d-block">
				<%= article.favorites.count %>
			</div>
			<span class="h5"><%= fa_icon("thumbs-up") %></span>
			<span class="font-weight-bold d-md-inline d-none">
				<%= article.favorites.count %>
			</span>
		</span>

	<% end %>

<% else %>

	<%= link_to article_favorites_path(article), style: "text-decoration: none;" , method: :post, id: "favorite-link", remote: true do %>

		<span class="list-group-item list-group-item-action nav-font mb-2">
			<div class="font-weight-bold d-md-none d-block">
				<%= article.favorites.count %>
			</div>
			<span class="h5"><%= fa_icon("thumbs-up") %></span>
			<span class="font-weight-bold d-md-inline d-none">
				<%= article.favorites.count %>
			</span>
		</span>

	<% end %>

<% end %>

app/views/favorites/create.js.erb
$("#favorite-of-<%= @article.id %>").html("<%= j(render partial: 'favorite', locals: { article: @article }) %>")
$("#user-ranking").html("<%= j(render 'articles/user_ranking') %>")
$("#eblities-point-of-<%= @user.id %>").html("<%= j(render 'users/point', user: @user) %>")
$("#flash-message").html("<%= j(render 'layouts/flash_message', flash_message: @flash_message) %>")

app/views/favorites/destroy.js.erb
$("#favorite-of-<%= @article.id %>").html("<%= j(render partial: 'favorite', locals: { article: @article }) %>")
$("#user-ranking").html("<%= j(render 'articles/user_ranking') %>")
$("#eblities-point-of-<%= @user.id %>").html("<%= j(render 'users/point', user: @user) %>")
$("#flash-message").html("<%= j(render 'layouts/flash_message', flash_message: @flash_message) %>")