config/routes.rb
Rails.application.routes.draw do

  resources 'uploads', only: [:create, :destroy]

  # root
  root to: 'articles#index'

  # devise
  # devise_for :admins, controllers: {
  # sessions:      'admins/sessions',
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
  # }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  resource :two_factor_auth, only: [:new, :create, :destroy]

  # admins
  # resources :admins, only: [ :index, :create, :edit, :show, :update]

  # get 'admins/:id/password', to: 'admins#password', as: 'admin_password_setting'

  # get 'admins/:id/profile', to: 'admins#profile', as: 'admin_profile'

  # get 'admins/:id/two_factor_authentication', to: 'admins#two_factor_authentication', as: 'admin_two_factor_authentication'

  # users
  resources :users, only: [ :index, :create, :edit, :show, :update] do
    resources :drafts do
      member do
        get 'confirm'
        post 'create_article'
      end
    end
    member do
     get :following, :followers
    end
  end

  get 'users/:id/favorites', to: 'users#favorites', as: 'favorites'

  get 'users/:id/comments', to: 'users#comments', as: 'comments'

  get 'users/:id/followers', to: 'users#followers', as: 'followers'

  get 'users/:id/followings', to: 'users#followings', as: 'followings'

  # get 'users/:id/account', to: 'users#account', as: 'user_account'

  get 'users/:id/password', to: 'users#password', as: 'user_password_setting'

  patch 'users/:id/update_password', to: 'users#update_password', as: 'update_password'

  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'

  get 'users/:id/two_factor_authentication', to: 'users#two_factor_authentication', as: 'user_two_factor_authentication'

  get 'users/:id/confirm_unsubscribe', to: 'users#confirm_unsubscribe', as: 'confirm_unsubscribe'

  patch 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'

  # relationships
  resources :relationships, only: [:create, :destroy]

  # articles
  resources :articles do
    resources :comments, only: [ :index, :create, :show, :update, :destroy]
    # resource :images, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :keeps, only: [:create, :destroy]
    collection do
      post 'confirm'
    end
  end

  get 'user_timeline', to: 'articles#user_timeline', as: 'user_timeline'

  get 'tag_timeline', to: 'articles#tag_timeline', as: 'tag_timeline'

  get 'articles/:id/confirm_edit', to: 'articles#confirm_edit', as: 'confirm_edit'

  # keeps
  resources :keeps, only: [:index]

  # tags
  resources :tags, only: [ :index, :create, :show ] do
    collection do
      post 'add'
    end
  end

  # taggings
  resources :taggings, only: [ :destroy]

  # contacts
  # resources :contacts, only: [ :index, :create, :new, :show, :update]

  # get 'contacts/confirm', to: 'contacts#confirm', as: 'confirm_contact'

  # get 'contacts/sent', to: 'contacts#sent', as: 'sent_contact'

  # terms
  # get 'terms', to: 'terms#index', as: 'terms'

  # help
  # get 'help', to: 'helps#index', as: 'helps'

  # about
  get 'about', to: 'abouts#about', as: 'about'

  # posts
  resources :posts

  # notifications
  resources :notifications

  get 'notifications/link_through'

  patch 'update_notification', to: 'notifications#update_notification', as: "update_notification"

  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/models/article.rb
class Article < ApplicationRecord

  attachment :image

  acts_as_taggable

  # Validatoin
  validates :title,
  	presence: true,
  	length: { maximum: 50,
              message: "タイトルは最大50文字まで入力できます" }

  validates :body,
  	presence: true,
  	length: { maximum: 10000,
              message: "本文は最大10000文字まで入力できます" }

  # Association
	belongs_to :user
	has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :keeps, dependent: :destroy
  has_many :tagging, as: :taggable, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # イイねしたかどうか
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # キープしたかどうか
  def kept_by?(user)
    keeps.where(user_id: user.id).exists?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]
  before_action :find_article, only: [:edit, :show, :confirm_edit, :update, :destroy]
  before_action :judge_user_id, only: [:edit, :confirm_edit, :update, :destroy]

  def user_timeline
    @search_post = Post.ransack(params[:q])
    @posts = @search_post.result.page(params[:page]).reverse_order
  end

  def confirm
    params[:article][:tag_list].split(",").each do |tag_name|
      if Tag.new(name: tag_name).invalid?
        new_article
        flash.now[:invalid_article] = "タグ1つにつき14文字までのタグ名を入力してください"
        render :new and return
      end
    end
    if params[:confirm_article]
      new_article
      if @article.invalid?
        flash.now[:invalid_article] = "入力内容を確認してください"
        render :new
      elsif @article.body == "<p><br></p>"
        flash.now[:invalid_article] = "本文を入力してください"
        render :new
      end
    elsif params[:create_draft]
      create_draft
      flash[:flash_message] = "下書きを保存しました"
      redirect_to user_drafts_path(current_user)
    end
  end

  def create
    if params[:create_article]
      new_article
      @article.save
      add_five_point
      create_post
      flash[:flash_message] = "記事を投稿しました。編集や削除はマイページで行えます。"
      redirect_to article_path(@article)
    elsif params[:create_draft]
      create_draft
      flash[:flash_message] = "下書きを保存しました"
      redirect_to user_drafts_path(current_user)
    elsif params[:back]
      new_article
      render :new
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @taggings = Tagging.where(taggable_type: "Article", taggable_id: @article.id)
  end

  def show
    @taggings = Tagging.where(taggable_type: "Article", taggable_id: @article.id)
    @user = User.find(@article.user_id)
    @comment = Comment.new
  end

  def update
    @article.tag_list.add(params[:article][:tag_list], parse: true)
    if params[:confirm_article]
      params[:article][:tag_list].split(",").each do |tag_name|
        if Tag.new(name: tag_name).invalid?
          flash.now[:invalid_article] = "タグ1つにつき14文字までのタグ名を入力してください"
          render :edit and return
        end
      end
      @article.title = article_params[:title]
      @article.body = article_params[:body]
      if @article.invalid?
        flash.now[:invalid_article] = "入力内容を確認してください"
        render :edit
      elsif @article.body == "<p><br></p>"
        flash.now[:invalid_article] = "本文を入力してください"
        render :edit
      else
        @article.update(article_params)
        redirect_to confirm_edit_path(@article)
      end
    elsif params[:create_article]
      @article.update(article_params)
      flash[:flash_message] = "編集した記事を投稿しました"
      redirect_to article_path(@article)
    elsif params[:create_draft]
      params[:article][:tag_list].split(",").each do |tag_name|
        if Tag.new(name: tag_name).invalid?
          flash.now[:invalid_article] = "タグ1つにつき14文字までのタグ名を入力してください"
          render :edit and return
        end
      end
      @draft = Draft.new(user_id: current_user.id, title: article_params[:title], body: article_params[:body], image: @article.image)
      @draft.save
      tagging_draft
      @article.destroy
      subtract_any_point
      flash[:flash_message] = "下書きとして投稿を取り下げました"
      redirect_to user_drafts_path(current_user)
    elsif params[:back]
      redirect_to edit_article_path(@article)
    end
  end

  def destroy
    destroy_post
    @article.destroy
    subtract_any_point
    flash[:flash_message] = "記事を削除しました"
    redirect_to user_path(@article.user_id)
  end





  private

  def find_article
    if Article.exists?(params[:id])
      @article = Article.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def judge_user_id
    unless @article.user_id == current_user.id
      redirect_to root_path(current_user)
    end
  end

  def new_article
    @article = Article.new( user_id: current_user.id,
                            title: article_params[:title],
                            body: article_params[:body],
                            image: article_params[:image],
                            tag_list: article_params[:tag_list] )
    @article.tag_list.add(article_params[:tag_list], parse: true)
  end

  def create_draft
    @draft = Draft.new(user_id: current_user.id, title: article_params[:title], body: article_params[:body], image: article_params[:image])
    @draft.save
    tagging_draft
  end

  def tagging_draft
    params[:article][:tag_list].split(",").each do |tag_name|
      if Tag.exists?(name: tag_name)
        @tag = Tag.find_by(name: tag_name)
        if Tagging.exists?(tag_id: @tag.id, taggable_type: "Draft", taggable_id: @draft.id)
        else
          Tagging.create(tag_id: @tag.id, taggable_type: "Draft", taggable_id: @draft.id, context: "tags")
        end
      else
        Tag.create(name: tag_name)
        @tag = Tag.find_by(name: tag_name)
        Tagging.create(tag_id: @tag.id, taggable_type: "Draft", taggable_id: @draft.id, context: "tags")
      end
    end
  end

  def create_post
    Post.create(
                user_id: @article.user_id,
                posted_by_id: current_user.id,
                article_id: @article.id,
                posted_type: "投稿")
  end

  def destroy_post
    post = Post.find_by(
                    user_id: @article.user_id,
                    posted_by_id: current_user.id,
                    article_id: @article.id,
                    posted_type: "投稿")
    post.destroy
  end

  def article_params
    params.require(:article).permit(:user_id, :title, :body, :image, :tag_list)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<% if article.comments.exists? %>

  <div class="mt-4" style="max-height: 800px; overflow: scroll;">

    <table class="table bg-white">
      <tbody>

        <% article.comments.each do |comment| %>
          <tr>
            <td>
              <p class="text-dark">
                <%= attachment_image_tag comment.user, :image, fallback: "no_image.jpg", class: "card-img mx-1", style: "max-height: 40px; max-width: 40px;"%>
                <%= link_to comment.user.user_name, user_path(comment.user_id) %>
              </p>
              <span class="text-secondary small">
                <%= comment.created_at.strftime('%Y/%m/%d %R') %>
              </span>

              <% if user_signed_in? %>

                <% if comment.user_id == current_user.id %>

                  <span class="ml-3 text-secondary">
                    <%= fa_icon("trash") %>
                    <%= link_to "削除する", article_comment_path(article_id: article, id: comment.id), method: :delete, "data-confirm" => "コメントを削除しますか？", class: "text-secondary small" %>
                  </span>

                <% end %>

              <% end %>

              <div class="mt-1 small text-dark">
                <%= raw comment.comment %>
              </div>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

  </div>

<% else %>

  <div class="mt-5" style="max-height: 400px; overflow: scroll;">

    <p class="text-center text-secondary small">コメントはありません</p>

  </div>

<% end %>

<% if user_signed_in? %>

  <div class="mt-5">
    <p>
      <%= attachment_image_tag current_user, :image, fallback: "no_image.jpg", class: "card-img mx-1", style: "max-height: 40px; max-width: 40px;"%>
      <span class="text-dark">コメント</span>
    </p>

    <%= simple_form_for [article,comment] do |f| %>
      <%= f.input :comment, label: false, class: "form-cotrol col-12",  id: "comment", placeholder: "コメント *500文字まで", error: "コメントを入力してください", type: "text", as: :summernote %>
      <p class="text-center">
        <%= f.submit "コメントを投稿する", class: "btn-sm btn-outline-success mt-2", id: "button" %>
      </p>
    <% end %>

  </div>

<% end %>

app/views/articles/_description_of_tag_timeline.html.erb
<h5 class="text-center mt-2">
  <%= link_to "タグタイムライン", tag_timeline_path, class: "border-bottom" %>
</h5>

<div class="px-2">
  タグタイムラインでは、あなたが登録しているタグの最新記事を見ることができます。
</div>
<p class="text-center mt-2">
  <a class="text-secondary" data-toggle="collapse" href="#collapseTagtimelineSm" role="button" aria-expanded="false" aria-controls="collapseTagtimelineSm">
    もっと詳しく!
  </a>
</p>
<div class="collapse p-2" id="collapseTagtimelineSm">

  <p>
    "<%= link_to "タグを探す", tags_path %>"であなたの興味のある分野をタグとして登録できます。"<%= link_to "マイページ", user_path(current_user) %>"でもタグを登録することができます。登録後、あなたの登録したタグの最新記事がタグタイムラインに表示されます。
  </p>

  <ul>
    <span>タグは他にも・・・</span>
    <li>記事と関連のある分野として、記事にタグを登録することもできます。</li>
    <li>記事にタグを登録すると、他のユーザーがその記事を見つけやすくなります。</li>
  </ul>

  記事にも積極的にタグを登録しましょう！

</div>

app/views/articles/_description_of_user_timeline.html.erb
<h5 class="text-center mt-2">
	<%= link_to "ユーザータイムライン", user_timeline_path, class: "border-bottom" %>
</h5>

<div class="px-2">
	ユーザータイムラインでは、あなたがフォローしているユーザーの投稿、イイね、キープ、コメントした記事を見ることができます。
</div>
<p class="text-center mt-2">
  <a class="text-secondary" data-toggle="collapse" href="#collapseUsertimelineSm" role="button" aria-expanded="false" aria-controls="collapseUsertimelineSm">
    もっと詳しく!
  </a>
</p>
<div class="collapse p-2" id="collapseUsertimelineSm">

  <p>
  	"<%= link_to "最新記事", articles_path %>"や"<%= link_to "タグを探す", tags_path %>"で良い記事を投稿しているユーザーを見つけたり、
  	"<%= link_to "ユーザーを探す", users_path %>"で興味のあるユーザーを見つけたらフォローしてみましょう。あなたのユーザータイムラインにフォローしているユーザーの投稿、イイね、キープ、コメントした記事が表示されます。
  </p>

	<ul>
		<span>あなたがフォローされると・・・</span>
		<li>2EP入手できます。</li>
		<li>フォロワー(あなたをフォローしているユーザー)のタイムラインにあなたの投稿、イイね、キープ、コメントした記事が表示されるので、あなたの記事が多くの人に読んでもらえるかもしれません。</li>
	</ul>

</div>

app/views/articles/confirm.html.erb
<%= simple_form_for(@article , url: {action: 'create'}) do |f| %>

	<%= render 'articles/confirm',  article: @article,
																	f: f,
	                                article_type: "article",
	                                submit_label: "下書きとして保存する",
	                                submit_name: "create_draft",
                                  submit_confirm: "現在の内容を下書きとして保存しますか？" %>

<% end %>

app/views/articles/index.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">

		<% unless user_signed_in? %>

			<div class="col-12 favorite-bg-color text-white align" style="min-height: 250px; margin-top: -25px;">

				<div class="row text-center h-100 align-items-center">

					<div class="col-lg-6 col-12 mt-lg-0 mt-3">
						<h1 style="letter-spacing: 1em; font-size: 14px;">エブリティーズ</h1>
						<h1 style="letter-spacing: 0.3em;">Eblities</h1>
						<h5 style="letter-spacing: 0.1em;">
							知りたいことがきっと見つかる。
						</h5>
						<p>クリエイターの知識をシェアするサイト。</p>
					</div>

					<div class="col-lg-6 col-12 mt-lg-0 mt-3">
						<p><%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-light" %></p>
						<p><%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-light" %></p>

					</div>

				</div>

			</div>

		<% end %>

		<div class="col-12 text-center text-success">

		</div>

		<div class="left-sidebar col-lg-2">

			<%= render 'articles/nav_bar' %>

		</div>

		<div class="col-lg-7 col-sm-11 content-margin">

      <div class="border rounded small bg-white d-lg-none mb-lg-0 mb-3">

      	<%= render 'articles/description_of_articles_index' %>

      </div>

			<% if Article.exists? %>
				<% if @search.result.count > 0 %>

				  <table class="table bg-white" id="articles">
					  <thead>
					    <tr>
					    	<th>
				    			<span><%= @articles.count %>件の記事</span>
					    	</th>
					    </tr>
					  </thead>

		    		<% if params[:q].present? %>
		    			<% if params[:q][:title_or_body_cont] != "" %>
			    			<p class="text-center font-weight-bold my-3">"<%= params[:q][:title_or_body_cont] %>"の検索結果</p>
		    			<% end %>
		    		<% end %>

				    <tbody class="page" id="all-articles" >

				    	<%= render 'articles/articles', articles: @articles %>

				    </tbody>
				  </table>

			  <% elsif @search.result.count == 0 %>

			  	<p class="text-center font-weight-bold mt-3">"<%= params[:q][:title_or_body_cont] %>"を含む記事はありません</p>

	        <p class="text-center mt-2">
	          <%= link_to "記事一覧へ戻る", articles_path, class: "border-bottom" %>
	        </p>

			 	<% end %>

	    <% else %>

			  <table class="table bg-white">
				  <thead>
				    <tr>
				    	<th class="text-center">
			    			<span>記事がありません</span>
				    	</th>
				    </tr>
				  </thead>
				</table>

	    <% end %>

	    <div class="row justify-content-center">
	    		<p class="col-12"><%= paginate @articles %></p>
	    </div>

	  </div>

	  <div class="col-lg-3 col-sm-11 content-margin">

      <div class="border rounded small bg-white d-lg-block d-none">

      	<%= render 'articles/description_of_articles_index' %>

      </div>

			<table class="table bg-white mt-3">

				<%= render 'articles/user_ranking' %>

			</table>

			<table class="table bg-white">

				<%= render 'articles/tag_ranking' %>

			</table>

		</div>

	</div>
</div>

app/views/articles/tag_timeline.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">

		<div class="left-sidebar col-lg-2 d-none d-lg-block">

			<%= render 'articles/nav_bar' %>

		</div>

		<div class="col-lg-7 col-sm-11 content-margin">

			<div class="border rounded small bg-white d-lg-none mb-lg-0 mb-3">

				<%= render 'articles/description_of_tag_timeline' %>

			</div>

			<% if current_user.tag_list.present? %>

			  <table class="table bg-white">

				  <thead>
				    <tr>
				    	<th>
					    	<div class="row">
					    		<div class="col-12">
					    			<span><%= current_user.taggings.count %>種類のタグを登録中</span>
					    		</div>
					    	</div>
				    	</th>
				    </tr>
				  </thead>

			    <tbody>

            <% current_user.taggings.page(params[:q]).each do |tagging| %>

              <%= render 'tags/tags', tags: Tag.where(id: tagging.tag_id) %>

            <% end %>

			    </tbody>

			  </table>

	    <% else %>

			  <table class="table bg-white">
				  <thead>
				    <tr>
				    	<th>
			    			<span>タグタイムライン</span>
				    	</th>
				    </tr>
				  </thead>
				</table>

				<p class="text-center font-weight-bold">
					関心のあるタグを登録していません
				</p>

	    <% end %>

	  </div>

	  <div class="col-lg-3 col-sm-11 content-margin">

			<div class="border rounded small bg-white d-lg-block d-none">

				<h5 class="text-center mt-2">
				  <%= link_to "タグタイムライン", tag_timeline_path, class: "border-bottom" %>
				</h5>

				<div class="px-2">
				  タグタイムラインでは、あなたが登録しているタグの最新記事を見ることができます。
				</div>
				<p class="text-center mt-2">
				  <a class="text-secondary" data-toggle="collapse" href="#collapseTagtimeline" role="button" aria-expanded="false" aria-controls="collapseTagtimeline">
				    もっと詳しく!
				  </a>
				</p>
				<div class="collapse p-2" id="collapseTagtimeline">

				  <p>
				    "<%= link_to "タグを探す", tags_path %>"であなたの興味のある分野をタグとして登録できます。"<%= link_to "マイページ", user_path(current_user) %>"でもタグを登録することができます。登録後、あなたの登録したタグの最新記事がタグタイムラインに表示されます。
				  </p>

				  <ul>
				    <span>タグは他にも・・・</span>
				    <li>記事と関連のある分野として、記事にタグを登録することもできます。</li>
				    <li>記事にタグを登録すると、他のユーザーがその記事を見つけやすくなります。</li>
				  </ul>

				  記事にも積極的にタグを登録しましょう！

				</div>

			</div>

			<table class="table bg-white mt-3">

				<%= render 'articles/tag_ranking' %>

			</table>

		</div>

	</div>
</div>

app/views/articles/user_timeline.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">

		<div class="left-sidebar col-lg-2 d-none d-lg-block">

			<%= render 'articles/nav_bar' %>

		</div>

		<div class="col-lg-7 col-sm-11 content-margin">

			<div class="border rounded small bg-white d-lg-none mb-lg-0 mb-3">

				<%= render 'articles/description_of_user_timeline' %>

			</div>

			<% if current_user.followings.present? %>

			  <table class="table bg-white">
				  <thead>
				    <tr>
				    	<th>
					    	<div class="row">
					    		<div class="col-12">
					    			<span>フォロー<%= current_user.followings.count %></span>
					    			/
					    			<span>フォロワー<%= current_user.followers.count %></span>
					    		</div>
					    	</div>
				    	</th>
				    </tr>
				    <tr>
				    	<td>
				    		<div class="row">
				    			<div class="col-12 text-center mb-2">
				    				絞り込み
				    			</div>
				    			<div class="col-12 text-center mb-2">
				    				<%= link_to "全て表示", user_timeline_path, class: "btn btn-secondary text-white " %>
				    			</div>
				    			<div class="col-md-3 col-6">
								    <%= search_form_for @search_post, url: user_timeline_path do |f| %>
								        <%= f.hidden_field :posted_type_eq, value: '投稿' %>
								        <%= f.button "投稿", class: "btn btn-default post-bg-color text-white w-100" %>
								    <% end %>
				    			</div>
				    			<div class="col-md-3 col-6">
								    <%= search_form_for @search_post, url: user_timeline_path do |f| %>
								        <%= f.hidden_field :posted_type_eq, value: 'イイね' %>
								        <%= f.button "イイね", class: "btn btn-default favorite-bg-color text-white w-100" %>
								    <% end %>
				    			</div>
				    			<div class="col-md-3 col-6 mt-md-0 mt-3">
								    <%= search_form_for @search_post, url: user_timeline_path do |f| %>
								        <%= f.hidden_field :posted_type_eq, value: 'キープ' %>
								        <%= f.button "キープ", class: "btn btn-default keep-bg-color text-white w-100" %>
								    <% end %>
				    			</div>
				    			<divc class="col-md-3 col-6 mt-md-0 mt-3">
								    <%= search_form_for @search_post, url: user_timeline_path do |f| %>
								        <%= f.hidden_field :posted_type_eq, value: 'コメント' %>
								        <%= f.button "コメント", class: "btn btn-default comment-bg-color text-white w-100" %>
								    <% end %>
				    			</div>
				    		</div>
				    	</td>
				    </tr>
				  </thead>

			    <tbody>
			    	<% @posts.where.not(posted_by_id: current_user.id, user_id: current_user.id).each do |post| %>
				    	<% if Relationship.find_by(follower_id: current_user.id, following_id: post.posted_by_id) %>

				    		<% user = User.find(post.posted_by_id) %>

								<tr>
								  <td>
								    <div class="card">
								      <div class="card-header" style="position: relative;">
								        <div class="row">

								          <div class="col-12 ranking-table">
								          	<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: " mx-1", style: "max-height: 40px; max-width: 40px;"%>

								          	<span>
								          		<%= link_to user.user_name, user_path(user) %>
								          	</span>

								          	<span class="small text-dark" style="font-weight: bold; font-size: 14px;">
								          		<% if post.posted_type == "投稿" %>

									          		<%= "さんが記事を" %>
									          		<span class="post-color">
									          			<%= "#{post.posted_type}" %>
								          			</span>
								          			<%= "しました" %>

								          		<% elsif post.posted_type == "イイね" %>

									          		<%= "さんが記事に" %>
									          		<span class="favorite-color">
									          			<%= "#{post.posted_type}" %>
								          			</span>
								          			<%= "をしました" %>

								          		<% elsif post.posted_type == "キープ" %>

									          		<%= "さんが記事を" %>
									          		<span class="keep-color">
									          			<%= "#{post.posted_type}" %>
								          			</span>
								          			<%= "しました" %>


								          		<% elsif post.posted_type == "コメント" %>

									          		<%= "さんが記事に" %>
									          		<span class="comment-color">
									          			<%= "#{post.posted_type}" %>
								          			</span>
								          			<%= "しました" %>

									          	<% end %>
								          	</span>
								          </div>

								          <div class="col-12 small text-secondary text-right" style="position: absolute; top: 0;" >
								          	<span>
								          		posted by : <%= user.user_name %>
								          	</span>

								          	<span class="ml-1">
								          		<%= post.user.point %>EP
								          	</span>

								          </div>

								          <div class="col-12 small text-secondary text-right" style="position: absolute; bottom: 0;" >

								          	<span>
								          		<%= post.created_at.strftime('%Y/%m/%d %R') %>
								          	</span>

								          </div>

								        </div>
								      </div>

								      <div class="card-body">

								      	<%= render 'articles/including_article', article: post.article, post: post %>

								      </div>
								    </div>
								  </td>
								</tr>

							<% end %>
						<% end %>

			    </tbody>
			  </table>

	    <% else %>

			  <table class="table bg-white">
				  <thead>
				    <tr>
				    	<th>
			    			<span>ユーザータイムライン</span>
				    	</th>
				    </tr>
				  </thead>
				</table>

				<p class="text-center font-weight-bold">
					フォロー中のユーザーがいません
				</p>

	    <% end %>

	  </div>

	  <div class="col-lg-3 col-sm-11 content-margin">

			<div class="border rounded small bg-white d-lg-block d-none">

				<h5 class="text-center mt-2">
					<%= link_to "ユーザータイムライン", user_timeline_path, class: "border-bottom" %>
				</h5>

				<div class="px-2">
					ユーザータイムラインでは、あなたがフォローしているユーザーの投稿、イイね、キープ、コメントした記事を見ることができます。
				</div>
				<p class="text-center mt-2">
				  <a class="text-secondary" data-toggle="collapse" href="#collapseUsertimeline" role="button" aria-expanded="false" aria-controls="collapseUsertimeline">
				    もっと詳しく!
				  </a>
				</p>
				<div class="collapse p-2" id="collapseUsertimeline">

				  <p>
				  	"<%= link_to "最新記事", articles_path %>"や"<%= link_to "タグを探す", tags_path %>"で良い記事を投稿しているユーザーを見つけたり、
				  	"<%= link_to "ユーザーを探す", users_path %>"で興味のあるユーザーを見つけたらフォローしてみましょう。あなたのユーザータイムラインにフォローしているユーザーの投稿、イイね、キープ、コメントした記事が表示されます。
				  </p>

					<ul>
						<span>あなたがフォローされると・・・</span>
						<li>2EP入手できます。</li>
						<li>フォロワー(あなたをフォローしているユーザー)のタイムラインにあなたの投稿、イイね、キープ、コメントした記事が表示されるので、あなたの記事が多くの人に読んでもらえるかもしれません。</li>
					</ul>

				</div>

			</div>

			<table class="table bg-white mt-3">

				<%= render 'articles/user_ranking' %>

			</table>

		</div>

	</div>
</div>