config/routes.rb
Rails.application.routes.draw do

  resources 'uploads', only: [:create, :destroy]

  # root
  root to: 'articles#index'

  # devise
  # devise_for :admins, controllers: {
  # sessions:      'admins/sessions',
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
  # }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  resource :two_factor_auth, only: [:new, :create, :destroy]

  # admins
  # resources :admins, only: [ :index, :create, :edit, :show, :update]

  # get 'admins/:id/password', to: 'admins#password', as: 'admin_password_setting'

  # get 'admins/:id/profile', to: 'admins#profile', as: 'admin_profile'

  # get 'admins/:id/two_factor_authentication', to: 'admins#two_factor_authentication', as: 'admin_two_factor_authentication'

  # users
  resources :users, only: [ :index, :create, :edit, :show, :update] do
    resources :drafts do
      member do
        get 'confirm'
        post 'create_article'
      end
    end
    member do
     get :following, :followers
    end
  end

  get 'users/:id/favorites', to: 'users#favorites', as: 'favorites'

  get 'users/:id/comments', to: 'users#comments', as: 'comments'

  get 'users/:id/followers', to: 'users#followers', as: 'followers'

  get 'users/:id/followings', to: 'users#followings', as: 'followings'

  # get 'users/:id/account', to: 'users#account', as: 'user_account'

  get 'users/:id/password', to: 'users#password', as: 'user_password_setting'

  patch 'users/:id/update_password', to: 'users#update_password', as: 'update_password'

  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'

  get 'users/:id/two_factor_authentication', to: 'users#two_factor_authentication', as: 'user_two_factor_authentication'

  get 'users/:id/confirm_unsubscribe', to: 'users#confirm_unsubscribe', as: 'confirm_unsubscribe'

  patch 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'

  # relationships
  resources :relationships, only: [:create, :destroy]

  # articles
  resources :articles do
    resources :comments, only: [ :index, :create, :show, :update, :destroy]
    # resource :images, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :keeps, only: [:create, :destroy]
    collection do
      post 'confirm'
    end
  end

  get 'user_timeline', to: 'articles#user_timeline', as: 'user_timeline'

  get 'tag_timeline', to: 'articles#tag_timeline', as: 'tag_timeline'

  get 'articles/:id/confirm_edit', to: 'articles#confirm_edit', as: 'confirm_edit'

  # keeps
  resources :keeps, only: [:index]

  # tags
  resources :tags, only: [ :index, :create, :show ] do
    collection do
      post 'add'
    end
  end

  # taggings
  resources :taggings, only: [ :destroy]

  # contacts
  # resources :contacts, only: [ :index, :create, :new, :show, :update]

  # get 'contacts/confirm', to: 'contacts#confirm', as: 'confirm_contact'

  # get 'contacts/sent', to: 'contacts#sent', as: 'sent_contact'

  # terms
  # get 'terms', to: 'terms#index', as: 'terms'

  # help
  # get 'help', to: 'helps#index', as: 'helps'

  # about
  get 'about', to: 'abouts#about', as: 'about'

  # posts
  resources :posts

  # notifications
  resources :notifications

  get 'notifications/link_through'

  patch 'update_notification', to: 'notifications#update_notification', as: "update_notification"

  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/models/notification.rb
class Notification < ApplicationRecord

 belongs_to :notified_by, class_name: 'User', optional: true
 belongs_to :user
 belongs_to :article, optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	before_action :authenticate_user

	def index
		@notifications = current_user.notifications.page(params[:page]).reverse_order
		@notifications.each do |notification|
			if notification.read == false
				notification.update(read: true)
			end
		end
	end

  def link_through
  	if Notification.exists?(params[:id])
	    @notification = Notification.find(params[:id])
	    if @notification.user_id == current_user.id
		    @notification.update read: true
				redirect_to article_path @notification.article
			else
				redirect_to root_path
			end
		else
			redirect_to root_path
		end
  end

  def update_notification
  	@unread_notifications = current_user.notifications.where(read: false)
  	@unread_notifications.each do |notification|
  		notification.update(read: true)
  	end
  	flash.now[:notification] = "通知を全て既読にしました"
  	@flash_notification = flash.now[:notification]
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li class="small my-1 text-center">

	<% if notification.notified_by_id.present? %>
		<% user = User.find(notification.notified_by_id) %>

		<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: "card-img", style: "max-height: 30px; max-width: 30px;"%>

		<%= link_to "#{user.user_name}", user_path(notification.user_id) %>さん<br>
	<% end %>

	<% if "#{notification.notified_type}" == "サインアップ" %>
		<p class="h5">
			ようこそEblitiesへ！
		</p>

		<p class="mx-4">
			ご登録ありがとうございます。Eblitiesは作曲家やデザイナーなど、様々な分野のクリエイターが知識を共有するサイトです。これからどうぞよろしくお願いします。サイトの簡単な使い方を<%= link_to "こちらのページ", notifications_path %>にてご案内させていただきます。
		</p>

		<p>
			プロフィール登録がお済みでない方は<br>
			<%= link_to "プロフィール設定", user_profile_path(current_user) %><br>
			で登録しましょう。
		</p>

		<p>
			アカウントのセキュリティを高めるために<br>
			<%= link_to "二段階認証の設定", user_two_factor_authentication_path(current_user) %><br>
			をオススメしています。
		</p>

	<% elsif "#{notification.notified_type}" == "キープ" %>

		<%= link_to "あなたの記事を#{notification.notified_type}しました", link_through_path(notification) %>

	<% elsif "#{notification.notified_type}" == "フォロー" %>

		<%= link_to "あなたを#{notification.notified_type}しました", followers_path(current_user) %>

	<% else %>

		<%= link_to "あなたの記事に#{notification.notified_type}をしました", link_through_path(notification) %>

	<% end %>

</li>

app/views/notifications/_notification_dropdown.html.erb
<button class="btn btn-default dropdown-toggle text-white" type="button" data-toggle="dropdown" id='dropdownMenu1' aria-haspopup="true"
aria-expanded="true" style="background-color: #125699;">
  <span class="small"><%= current_user.notifications.where(read: false).count %></span>
  <span class="glyphicon glyphicon-flag small"><i class="fa fa-bell" aria-hidden="true"></i>通知</span>
</button>

<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1" style="min-width: 300px;" >
  <li class="dropdown-header text-center">通知</li>

    <%= render current_user.notifications.where(read: false).order('created_at DESC').last(5) %>
    <% n = current_user.notifications.where(read: false) %>

    <% if n.blank? %>

      <li class="text-center small">未読の通知はありません</li>

    <% end %>

    <li class="divider" role="separator"> </li>
    <li class="text-center small mt-1">
    <p class="mt-3"><u><%= link_to '通知一覧を見る', notifications_path, class: "text-dark" %></u></p>

    <% if n.present? %>

      <p><u><%= link_to '全て既読にする', update_notification_path, method: :patch, remote: true, class: "text-dark" %></u></p>

    <% end %>
  </li>
</ul>

app/views/notifications/_notification_dropdown_sm.html.erb
<button class="btn btn-default dropdown-toggle text-white" type="button" data-toggle="dropdown" id='dropdownMenu1' aria-haspopup="true"
aria-expanded="true" style="background-color: #125699;">
  <span class="small"><%= current_user.notifications.where(read: false).count %></span>
  <span class="glyphicon glyphicon-flag small"><i class="fa fa-bell" aria-hidden="true"></i>通知</span>
</button>

<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1" style="min-width: 300px;" >
  <li class="dropdown-header text-center">通知</li>

    <%= render current_user.notifications.where(read: false).order('created_at DESC').last(5) %>
    <% n = current_user.notifications.where(read: false) %>

    <% if n.blank? %>

      <li class="text-center small">未読の通知はありません</li>

    <% end %>

    <li class="divider" role="separator"> </li>
    <li class="text-center small mt-1">
    <p class="mt-3"><u><%= link_to '通知一覧を見る', notifications_path, class: "text-dark" %></u></p>

    <% if n.present? %>

      <p><u><%= link_to '全て既読にする', update_notification_path, method: :patch, remote: true, class: "text-dark" %></u></p>

    <% end %>
  </li>
</ul>

app/views/notifications/index.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">

		<div class="left-sidebar col-lg-2">

			<%= render 'articles/nav_bar' %>

		</div>

		<div class="col-md-10 col-12" id="notifications">

			<p class="bg-navy rounded border text-white text-center font-weight-bold content-margin py-2"><%= current_user.user_name %>さんの通知一覧</p>

			<% @notifications.each do |notification| %>

				<ul class="list-group list-group-flush notification">

					<li class="list-group-item small my-2 page">

						<% if notification.notified_by_id.present? %>
							<% user = User.find(notification.notified_by_id) %>
							<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: "card-img", style: "max-height: 40px; max-width: 40px;"%>
							<%= link_to "#{user.user_name}", user_path(user) %>
								さんが
						<% end %>

							<% if "#{notification.notified_type}" == "サインアップ" %>
								<div class="row justify-content-center">

									<div class="text-center col-lg-8">
										<p class="h5">
											ようこそEblitiesへ！
										</p>

										<p class="mx-4">
											ご登録ありがとうございます。Eblitiesは作曲家やデザイナーなど、様々な分野のクリエイターが知識を共有するサイトです。これからどうぞよろしくお願いします。
										</p>

										<p>
											とりあえず記事を探したい場合は画面上部の検索フォームから検索ができます。
										</p>

										<p>
											まずは<%= link_to "タグを探す", tags_path %>であなたのタグリストに興味のあるタグを登録するのがオススメです。タグリストを作成すると<%= link_to "タグタイムライン", tag_timeline_path %>が使用できるようになり、気になるタグの最新記事をチェックできるようになります。
										</p>

										<p>
											気になるユーザーがいたらフォローしてみましょう。ユーザーをフォローすると<%= link_to "ユーザータイムライン", tag_timeline_path %>にて、そのユーザーの投稿、イイね、キープ、コメントした記事を見ることができます。
										</p>

										<p>
											イケてる記事を見つけたらイイねボタンを押して記事を評価しましょう。
										  <div class="btn border" id="favorite-demo"">
										  	<%= fa_icon('thumbs-up 2x') %>
										  </div>
										</p>

										<p>
											後で読みたい記事、気に入った記事を保存するには、キープボタンを押します。<%= link_to "キープ一覧", keeps_path %>でキープした記事を見ることができます。
										  <div class="btn border" id="keep-demo"">
										  	<%= fa_icon('folder-open 2x') %>
										  </div>
										</p>

										<p>
											EPとは？(Eblities Pointとは？)
										</p>

										<p>
											EP(Eblities Point)とは、ユーザーがどのくらい積極的にEblitiesを利用しているか測るためのポイントです。ポイントが最も多く貯まる要因は、良い記事を書いて多くのイイね、キープをしてもらうことですので、EPの多いユーザーほど積極的であると言えます。最もポイントの多いユーザーの上位10名はユーザーランキングに表示されます。EPは下記のイベントにより加算されます。
											<ul class="list-group">
												<li class="list-group-item">記事を投稿する +5EP</li>
											  <li class="list-group-item">フォローされる +2EP</li>
											  <li class="list-group-item">イイねされる +1EP</li>
											  <li class="list-group-item">キープされる +1EP</li>
											  <li class="list-group-item text-secondary">*イベントが取り消されるとその分減算されます。</li>
											</ul>
										</p>

										<p>
											プロフィール登録がお済みでない方は<br>
											<%= link_to "プロフィール設定", user_profile_path(current_user) %><br>
											で登録しましょう。
										</p>

										<p>
											アカウントのセキュリティを高めるために<br>
											<%= link_to "二段階認証の設定", user_two_factor_authentication_path(current_user) %><br>
											をオススメしています。
										</p>

										<p>
											ご案内は以上となります。主要なページの右上にも機能の説明が書いてありますので、機能をもう一度確認したい場合は是非ご活用ください。
										</p>

										<p>
											<%= link_to "TOP画面へ", root_path %>
										</p>

									</div>

								</div>

							<% elsif "#{notification.notified_type}" == "キープ" %>

							<%= link_to "あなたの記事を#{notification.notified_type}しました", link_through_path(notification) %>

							<br>
							記事 :
							<span>
								<%= link_to "#{notification.article.title}", article_path(notification.article_id) %>
							</span>

						<% elsif "#{notification.notified_type}" == "フォロー" %>

							<%= link_to "あなたを#{notification.notified_type}しました", followers_path(current_user) %>

						<% else %>

							<%= link_to "あなたの記事に#{notification.notified_type}をしました", link_through_path(notification) %>

							<br>
							記事 :
							<span>
								<%= link_to "#{notification.article.title}", article_path(notification.article_id) %>
							</span>

						<% end %>

					</li>

				</ul>

			<% end %>

	    <div class="row justify-content-center">
	    		<p class="col-12"><%= paginate @notifications %></p>
	    </div>

		</div>
	</div>
</div>

<script>
$(function(){
    $("#favorite-demo").on({
        "click":function(){
            $(this).addClass("favorite-bg-color text-white");
        }
    });
    $("#keep-demo").on({
        "click":function(){
            $(this).addClass("keep-bg-color text-white");
        }
    });
});
</script>

app/views/notifications/update_notification.js.erb
$("#flash-notification").html("<%= j(render 'layouts/flash_notification', flash_notification: @flash_notification, unread_notifications: @unread_notifications)  %>")
$("#notification_dropdown").html("<%= j(render 'notifications/notification_dropdown')  %>")
$("#notification_dropdown_sm").html("<%= j(render 'notifications/notification_dropdown_sm')  %>")