config/routes.rb
Rails.application.routes.draw do

  resources 'uploads', only: [:create, :destroy]

  # root
  root to: 'articles#index'

  # devise
  # devise_for :admins, controllers: {
  # sessions:      'admins/sessions',
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
  # }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  resource :two_factor_auth, only: [:new, :create, :destroy]

  # admins
  # resources :admins, only: [ :index, :create, :edit, :show, :update]

  # get 'admins/:id/password', to: 'admins#password', as: 'admin_password_setting'

  # get 'admins/:id/profile', to: 'admins#profile', as: 'admin_profile'

  # get 'admins/:id/two_factor_authentication', to: 'admins#two_factor_authentication', as: 'admin_two_factor_authentication'

  # users
  resources :users, only: [ :index, :create, :edit, :show, :update] do
    resources :drafts do
      member do
        get 'confirm'
        post 'create_article'
      end
    end
    member do
     get :following, :followers
    end
  end

  get 'users/:id/favorites', to: 'users#favorites', as: 'favorites'

  get 'users/:id/comments', to: 'users#comments', as: 'comments'

  get 'users/:id/followers', to: 'users#followers', as: 'followers'

  get 'users/:id/followings', to: 'users#followings', as: 'followings'

  # get 'users/:id/account', to: 'users#account', as: 'user_account'

  get 'users/:id/password', to: 'users#password', as: 'user_password_setting'

  patch 'users/:id/update_password', to: 'users#update_password', as: 'update_password'

  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'

  get 'users/:id/two_factor_authentication', to: 'users#two_factor_authentication', as: 'user_two_factor_authentication'

  get 'users/:id/confirm_unsubscribe', to: 'users#confirm_unsubscribe', as: 'confirm_unsubscribe'

  patch 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'

  # relationships
  resources :relationships, only: [:create, :destroy]

  # articles
  resources :articles do
    resources :comments, only: [ :index, :create, :show, :update, :destroy]
    # resource :images, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :keeps, only: [:create, :destroy]
    collection do
      post 'confirm'
    end
  end

  get 'user_timeline', to: 'articles#user_timeline', as: 'user_timeline'

  get 'tag_timeline', to: 'articles#tag_timeline', as: 'tag_timeline'

  get 'articles/:id/confirm_edit', to: 'articles#confirm_edit', as: 'confirm_edit'

  # keeps
  resources :keeps, only: [:index]

  # tags
  resources :tags, only: [ :index, :create, :show ] do
    collection do
      post 'add'
    end
  end

  # taggings
  resources :taggings, only: [ :destroy]

  # contacts
  # resources :contacts, only: [ :index, :create, :new, :show, :update]

  # get 'contacts/confirm', to: 'contacts#confirm', as: 'confirm_contact'

  # get 'contacts/sent', to: 'contacts#sent', as: 'sent_contact'

  # terms
  # get 'terms', to: 'terms#index', as: 'terms'

  # help
  # get 'help', to: 'helps#index', as: 'helps'

  # about
  get 'about', to: 'abouts#about', as: 'about'

  # posts
  resources :posts

  # notifications
  resources :notifications

  get 'notifications/link_through'

  patch 'update_notification', to: 'notifications#update_notification', as: "update_notification"

  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :name,
    presence: true,
    length: { maximum: 14,
              message: "タグの名前は1つにつき最大14文字まで入力できます" }

  has_many :taggings

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]
  before_action :set_user_info
  before_action :set_search_tag, only: [:index ,:create, :add]

  def index
    if user_signed_in?
      @taggings = Tagging.where(taggable_type: "User", taggable_id: current_user.id)
    end
  end

  def create
    if params[:user][:tag_list].blank?
      flash.now[:flash_message] = "14文字までのタグ名を入力してください" and return
    end
    params[:user][:tag_list].split(",").each do |tag_name|
      if Tag.new(name: tag_name).invalid?
        flash.now[:flash_message] = "14文字までのタグ名を入力してください" and return
      end
      if Tag.exists?(name: tag_name)
        tag = Tag.find_by(name: tag_name)
        unless Tagging.exists?(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id)
          Tagging.create(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id, context: "tags")
        end
      else
        Tag.create(name: tag_name)
        tag = Tag.find_by(name: tag_name)
        Tagging.create(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id, context: "tags")
      end
    end
    flash.now[:flash_message] = "タグリストを更新しました"
    @flash_message = flash.now[:flash_message]
  end

  def add
    tag_name = params[:user][:tag_list]
    if Tag.exists?(name: tag_name)
      tag = Tag.find_by(name: tag_name)
      unless Tagging.exists?(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id)
        Tagging.create(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id, context: "tags")
      end
    else
      Tag.create(name: tag_name)
      tag = Tag.find_by(name: tag_name)
      Tagging.create(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id, context: "tags")
    end
    @find_tag = Tag.find_by(name: tag_name)
    find_taggings
    flash.now[:flash_message] = "#{@find_tag.name}をあなたのタグリストに登録しました"
    @flash_message = flash.now[:flash_message]
  end

  def show
    if Tag.exists?(params[:id])
      @find_tag = Tag.find(params[:id])
      @search_tag_article = Article.tagged_with("#{@find_tag.name}").ransack(params[:q])
      @tag_articles = @search_tag_article.result.page(params[:page]).reverse_order
      find_taggings
    else
      redirect_to tags_path
    end
  end





  private

  def set_user_info
    if user_signed_in?
      @user = current_user
      @taggings = Tagging.where(taggable_type: "User", taggable_id: @user.id)
      @new_tag = Tag.new
    end
  end

  def find_taggings
    @tagging_articles = Tagging.where(tag_id: @find_tag.id, taggable_type: "Article")
    @tagging_users = Tagging.where(tag_id: @find_tag, taggable_type: "User")
  end

  def set_search_tag
    @search_tag = Tag.ransack(params[:q])
    @tags = @search_tag.result.page(params[:page]).reverse_order
  end

  def tag_params
    params.require(:tag).permit(:name, :taggings_count, :tag_list)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_common_users.html.erb
<table class="table table-sm bg-white card-body">
	<tbody>
	  <% current_user.find_related_tags.order("RANDOM()").limit(10).each do |user| %>
	    <tr>
	      <td class="right-sidebar-link">
	      	<p>
	      		<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: " mx-1", style: "max-height: 40px; max-width: 40px;"%>
	      		<%= link_to user.user_name, user_path(user) %>
	      	</p>
	      	<span class="small">あなたと共通のタグ</span>
	      	<% Tagging.where(taggable_type: "User", taggable_id: user).each do |tagging| %>
	      		<% Tagging.where(taggable_type: "User", taggable_id: current_user).each do |my_tagging| %>
	      			<% if tagging.tag.name == my_tagging.tag.name %>
				        <span class="badge tag-color p-1">
				        	<%= link_to tagging.tag.name, tag_path(tagging.tag.id),class: "text-white" %>
			        	</span>
			        <% end %>
			      <% end %>
		      <% end %>

		      <span id="relationship-of-<%= user.id %>">
			      <%= render 'relationships/follow_or_unfollow', user: user %>
			    </span>

	      </td>
	    </tr>
	  <% end %>
	</tbody>
</table>

app/views/tags/_description_of_tags_index.html.erb
<div class="border rounded small bg-white mb-lg-0 mb-3">

	<h5 class="text-center mt-2">
		<%= link_to "タグ一覧", tags_path, class: "border-bottom" %>
	</h5>

	<div class="px-2">
		投稿されている記事のタグの一覧です。あなたの関心のあるタグを見つけましょう。新しく自分でタグを登録することもできます。
	</div>
	<p class="text-center mt-2">
	  <a class="text-secondary" data-toggle="collapse" href="#collapseTagsSm" role="button" aria-expanded="false" aria-controls="collapseTagsSm">
	    タグとは？
	  </a>
	</p>
	<div class="collapse p-2" id="collapseTagsSm">

    <p>
    	タグとは記事に関係のある分野、もしくはあなたの関心のある分野を表します。エブリティーズには、クリエイティブな事に関係があればどんな分野の記事を投稿しても大丈夫です。積極的にタグを登録しましょう！
    </p>

  	<ul>
  		<span>記事にタグを登録すると・・・</span>
  		<li>タグタイムラインにあなたの記事が表示されます</li>
  		<li>タグ検索からあなたの記事を見つけられるようになります</li>
  	</ul>

  	<ul>
  		<span>ユーザー情報にタグを登録すると・・・</span>
  		<li>同じタグを登録しているユーザーを見つけたり、他のユーザーがあなたを見つけられたりできるようになります。</li>
  		<li>登録しているタグの最新記事が見られるタグタイムライン機能が使えるようになります。</li>
  	</ul>

    <p class="text-white">
      <span class="text-dark">例 :</span>
      <span class="badge d-inline tag-color">音楽</span>
      <span class="badge d-inline tag-color">DTM</span>
      <span class="badge d-inline tag-color">イラスト</span>
      <span class="badge d-inline tag-color">CG</span>
      <span class="badge d-inline tag-color">基礎知識</span>
    </p>

	</div>
</div>

<% if user_signed_in? %>

	<div class="d-lg-none text-center">
		<a href="#link">共通のタグユーザーを見る</a>
	</div>

<% end %>

app/views/tags/_description_of_tags_show.html.erb
<div class="card mb-3">
  <div class="card-header text-white text-center font-weight-bold" style ="background-color: #125699;">
  	タグ : <%= link_to tag.name, tag_path(tag), class: "text-white berder border-bottom" %>
  </div>
  <div class="card-body">

  	<% if user_signed_in? %>

	    <div class="text-center" id="tag-mark-of-<%= tag.id %>">

	      <%= render partial: 'tags/tag_mark', locals: {tag: tag} %>

	    </div>

	  <% end %>

  	<div class="small">
  		タグ : <%= link_to tag.name, tag_path(tag), class: "text-dark berder border-bottom" %>が登録されている記事の一覧です。
  	</div>

		<table class="table table-sm bg-white card-body text-center mt-2">
			<tbody>
		    <tr>
		      <th class="text-center">
		      	関心を持つユーザー
		      </th>
		    </tr>
		    <tr>
		      <td>
		      	<span class="text-secondary"><%= fa_icon("users") %></span>

		      	<span id="tagging-users-count-of-<%= tag.id %>">
			      	<%= render partial: 'tags/tagging_users_count', locals: {tagging_users: tagging_users} %>
		      	</span>

		      	<span class="small">名が登録</span>
		      </td>
		    </tr>
		    <tr>
		      <th class="text-center">
		      	タグ付けされた記事
		      </th>
		    </tr>
		    <tr>
		      <td>
		      	<span class="text-secondary"><%= fa_icon("pencil") %></span>
		      	<span>
			      	<%= tagging_articles.count %>
			      </span>
		      	<span class="small">件の記事</span>
		      </td>
		    </tr>
			</tbody>
		</table>

		<% if user_signed_in? %>

	    <div class="text-center" id="tag-button-of-<%= tag.id %>">

	      <%= render partial: 'tags/tag_button', locals: {tag: tag, new_tag: new_tag} %>

	    </div>

	  <% end %>

  </div>
</div>

app/views/tags/_description_of_tags_show_sm.html.erb
<div class="card mb-3">
  <div class="card-header text-white text-center font-weight-bold" style ="background-color: #125699;">
  	タグ : <%= link_to tag.name, tag_path(tag), class: "text-white berder border-bottom" %>
  </div>
  <div class="card-body">

  	<% if user_signed_in? %>

	    <div class="text-center" id="tag-mark-of-<%= tag.id %>-sm">

	      <%= render partial: 'tags/tag_mark', locals: {tag: tag} %>

	    </div>

	  <% end %>

  	<div class="small">
  		タグ : <%= link_to tag.name, tag_path(tag), class: "text-dark berder border-bottom" %>が登録されている記事の一覧です。
  	</div>

		<table class="table table-sm bg-white card-body text-center mt-2">
			<tbody>
		    <tr>
		      <th class="text-center">
		      	関心を持つユーザー
		      </th>
		    </tr>
		    <tr>
		      <td>
		      	<span class="text-secondary"><%= fa_icon("users") %></span>

		      	<span id="tagging-users-count-of-<%= tag.id %>-sm">
			      	<%= render partial: 'tags/tagging_users_count', locals: {tagging_users: tagging_users} %>
		      	</span>

		      	<span class="small">名が登録</span>
		      </td>
		    </tr>
		    <tr>
		      <th class="text-center">
		      	タグ付けされた記事
		      </th>
		    </tr>
		    <tr>
		      <td>
		      	<span class="text-secondary"><%= fa_icon("pencil") %></span>
		      	<span>
			      	<%= tagging_articles.count %>
			      </span>
		      	<span class="small">件の記事</span>
		      </td>
		    </tr>
			</tbody>
		</table>

		<% if user_signed_in? %>

	    <div class="text-center" id="tag-button-of-<%= tag.id %>-sm">

	      <%= render partial: 'tags/tag_button', locals: {tag: tag, new_tag: new_tag} %>

	    </div>

	  <% end %>

  </div>
</div>

<% if user_signed_in? %>

	<div class="text-center">
		<a href="#link">"<%= tag.name %>"に関心を持つ他のユーザーを見る</a>
	</div>

<% end %>

app/views/tags/_tag_button.html.erb
<% if tag.taggings.exists?(taggable_type: "User", taggable_id: current_user.id) %>

  <span>
    <% tagging = Tagging.find_by(tag_id: tag.id, taggable_type: "User", taggable_id: current_user.id) %>
    <%= link_to "タグリストから削除する",tagging_path(tagging.id), class: "btn btn-outline-secondary btn-sm", method: :delete, remote: true %>
  </span>

<% else %>

  <span>
    <%= form_for(new_tag, url: {controller: "tags" ,action: "add"}, remote: true) do |f| %>
      <span class="d-none">
      <%= text_field_tag 'user[tag_list]', current_user.tag_list.join(','), value: "#{tag.name}" %>
      </span>
      <%= f.submit "タグリストに登録する", class: "btn btn-outline-primary btn-sm" %>
    <% end %>
  </span>

<% end %>

app/views/tags/_tag_mark.html.erb
<% if tag.taggings.exists?(taggable_type: "User", taggable_id: current_user.id) %>
  <span class="badge badge-primary">
    登録中
  </span>
<% end %>

app/views/tags/_tag_users.html.erb
<table class="table table-sm bg-white card-body">
	<tbody >
	  <% User.tagged_with(tag.name).order("RANDOM()").limit(10).each do |user|  %>
		  <% if user != current_user %>

		    <tr>
		      <td class="right-sidebar-link">
		      	<p>
		      		<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: " mx-1", style: "max-height: 40px; max-width: 40px;"%>
		      		<%= link_to user.user_name, user_path(user) %>
		      	</p>

			      	<span class="small">あなたと共通のタグ</span>
			      	<% Tagging.where(taggable_type: "User", taggable_id: user).each do |tagging| %>
			      		<% Tagging.where(taggable_type: "User", taggable_id: current_user).each do |my_tagging| %>
			      			<% if tagging.tag.name == my_tagging.tag.name %>
						        <span class="badge tag-color p-1">
						        	<%= link_to tagging.tag.name, tag_path(tagging.tag.id),class: "text-white" %>
					        	</span>
					        <% end %>
					      <% end %>
				      <% end %>

			      <span id="relationship-of-<%= user.id %>">
				      <%= render 'relationships/follow_or_unfollow', user: user %>
				    </span>

		      </td>
		    </tr>
		  <% end %>
	  <% end %>
	</tbody>
</table>

app/views/tags/_tagging_users_count.html.erb
<%= tagging_users.count %>

app/views/tags/_tags.html.erb
<% tags.each do |tag| %>

  <% tagging_articles = Tagging.where(tag_id: tag.id, taggable_type: "Article") %>
  <% tagging_users = Tagging.where(tag_id: tag.id, taggable_type: "User") %>

  <tr class="tag">
    <td>
      <div class="card">
        <div class="card-header">
          <div class="row">

            <div class="col-6 ranking-table">
            	<span class="badge tag-color p-1">
            		<%= link_to tag.name, tag_path(tag), class: "text-white" %>
            	</span>

              <% if tagging_articles.present? %>

                <span class="small tag-title-font">
                  の最新記事
                </span>

              <% else %>

                <span class="small tag-title-font">
                  の記事はまだありません
                </span>

              <% end %>

            </div>

            <div class="col-6 small text-secondary text-right align-self-center">

            	<span>
            		<%= fa_icon("pencil") %><%= tagging_articles.count %>件の記事
            	</span>

              <br>

              <%= fa_icon("users") %>
            	<span id="tagging-users-count-of-<%= tag.id %>">
                <%= render partial: 'tags/tagging_users_count', locals: {tagging_users: tagging_users} %>
            	</span>
              名が登録

            </div>

            <% if controller_name == "tags" && user_signed_in? %>

              <div class="col-6" id="tag-button-of-<%= tag.id %>">

                <%= render partial: 'tags/tag_button', locals: {tag: tag, new_tag: new_tag} %>

              </div>

              <div class="col-6 text-right" id="tag-mark-of-<%= tag.id %>">

                <%= render partial: 'tags/tag_mark', locals: {tag: tag} %>

              </div>

            <% end %>

          </div>
        </div>

        <% tagging_articles.last(1).each do |tagging_article| %>

          <div class="card-body">

            <%= render 'articles/including_article', article: tagging_article.taggable %>

          </div>

        <% end %>

      </div>
    </td>
  </tr>

<% end %>

app/views/tags/add.js.erb
$("#tags_input_style").html("<%= j(render 'layouts/tags_input_style') %>")
$("#modal-tagging-list-of-<%= @user.id %>").html("<%= j(render 'taggings/modal_tagging_list', taggings: @taggings) %>")
$("#modal-tagging-form-of-<%= @user.id %>").html("<%= j(render 'taggings/modal_tagging_form', new_tag: @new_tag, user: @user ) %>")
$("#tagging-list-of-<%= @user.id %>").html("<%= j(render 'taggings/tagging_list', taggings: @taggings, user: @user) %>")
$("#common-users-of-<%= @user.id %>").html("<%= j(render partial: 'common_users') %>")
$("#tag-users").html("<%= j(render partial: 'tag_users', locals: {tag: @find_tag} ) %>")
$("#tag-button-of-<%= @find_tag.id %>").html("<%= j(render partial: 'tag_button', locals: {tag: @find_tag} ) %>")
$("#tag-button-of-<%= @find_tag.id %>-sm").html("<%= j(render partial: 'tag_button', locals: {tag: @find_tag} ) %>")
$("#tagging-users-count-of-<%= @find_tag.id %>").html("<%= j(render partial: 'tagging_users_count', locals: {tagging_users: @tagging_users }) %>")
$("#tagging-users-count-of-<%= @find_tag.id %>-sm").html("<%= j(render partial: 'tagging_users_count', locals: {tagging_users: @tagging_users }) %>")
$("#tag-mark-of-<%= @find_tag.id %>").html("<%= j(render partial: 'tag_mark', locals: {tag: @find_tag} ) %>")
$("#tag-mark-of-<%= @find_tag.id %>-sm").html("<%= j(render partial: 'tag_mark', locals: {tag: @find_tag} ) %>")
$("#flash-message").html("<%= j(render 'layouts/flash_message', flash_message: @flash_message) %>")
$("#tags_input_script").html("<%= j(render 'layouts/tags_input_script') %>")

app/views/tags/create.js.erb
$("#tags_input_style").html("<%= j(render 'layouts/tags_input_style') %>")
$("#modal-tagging-list-of-<%= @user.id %>").html("<%= j(render 'taggings/modal_tagging_list', taggings: @taggings) %>")
$("#modal-tagging-form-of-<%= @user.id %>").html("<%= j(render 'taggings/modal_tagging_form', new_tag: @new_tag, user: @user ) %>")
$("#tagging-list-of-<%= @user.id %>").html("<%= j(render 'taggings/tagging_list', taggings: @taggings, user: @user) %>")
$("#common-users-of-<%= @user.id %>").html("<%= j(render partial: 'common_users') %>")
$("#all-tags").html("<%= j(render partial: 'tags/tags', locals: {tags: @tags, new_tag: @new_tag, user: @user} ) %>")
$("#flash-message").html("<%= j(render 'layouts/flash_message', flash_message: @flash_message) %>")
$("#tags_input_script").html("<%= j(render 'layouts/tags_input_script') %>")

app/views/tags/show.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">

		<div class="left-sidebar col-lg-2 d-none d-lg-block">

			<%= render 'articles/nav_bar' %>

		</div>

		<div class="d-lg-none col-sm-11 content-margin">

			<%= render partial: 'tags/description_of_tags_show_sm',
								 locals: {tag: @find_tag,
													new_tag: @new_tag,
													tagging_users: @tagging_users,
													tagging_articles: @tagging_articles,
													new_tag: @new_tag} %>

		</div>

		<div class="col-lg-7 col-sm-11 content-margin">

	    <%= search_form_for @search_tag_article, url: tag_path do |f| %>
	      <div class="form-inline mb-2">
	        <%= f.text_field :title_or_body_cont, class: "col-sm-10 col-xs-12 form-control", placeholder: "#{@find_tag.name}の記事を検索" %>
	        <%= f.button fa_icon("search"), class: 'col-sm-2 col-xs-12 btn btn-outline-dark my-lg-0 my-2'%>
	      </div>
	    <% end %>

			<% if Article.tagged_with("#{@find_tag.name}").exists? %>
				<% if @search_tag_article.result.count > 0 %>

				  <table class="table bg-white" id="articles">
					  <thead>
					    <tr>
					    	<th>
				    			<span>
				    				<%= link_to @find_tag.name, tag_path(@find_tag), class: "text-white rounded px-1 tag-color" %>
				    				がタグ付けされた記事一覧 : <%= @search_tag_article.result.count %>件
				    			</span>
					    	</th>
					    </tr>
					  </thead>

		    		<% if params[:q].present? %>
		    			<% if params[:q][:title_or_body_cont] != "" %>
			    			<p class="text-center font-weight-bold my-3">"<%= params[:q][:title_or_body_cont] %>"の検索結果</p>
		    			<% end %>
		    		<% end %>

				    <tbody class="page" id="tag-articles">

				    	<%= render partial: 'articles/articles', locals: {articles: @tag_articles} %>

					  </tbody>
					</table>

			  <% elsif @search_tag_article.result.count == 0 %>
			  	<p class="text-center">
			  		<span class="">
			  			<%= link_to @find_tag.name, tag_path(@find_tag), class: "text-white rounded px-1 tag-color" %> がタグ付けされた記事を検索
		  			</span>
			  	</p>
			  	<p class="text-center font-weight-bold mt-3">
			  		"<%= params[:q][:title_or_body_cont] %>"を含む記事はありません
			  	</p>

			 	<% end %>

	    <% else %>

				<p class="text-center font-weight-bold"><span class="text-white rounded px-1 tag-color"><%= @find_tag.name %></span> がタグ付けされた記事はありません</p>

	    <% end %>

	    <div class="row justify-content-center">
	    		<p class="col-12"><%= paginate @tag_articles %></p>
	    </div>

	  </div>

		<div class="col-lg-3 col-sm-11 content-margin">
			<div class="row">
				<div class="col-12 d-lg-block d-none">

					<%= render partial: 'tags/description_of_tags_show',
										 locals: {tag: @find_tag,
															new_tag: @new_tag,
															tagging_users: @tagging_users,
															tagging_articles: @tagging_articles,
															new_tag: @new_tag} %>

				</div>

		    <% if user_signed_in? %>

		    	<a name="link"></a>

					<div class="col-12">
						<div class="card mb-3">

						  <div class="card-header text-center font-weight-bold">
						  	"<%= @find_tag.name %>"に関心を持つ他のユーザー
						  </div>
						  <div class="card-body" id="tag-users">

								<%= render partial: 'tags/tag_users',locals: {tag: @find_tag} %>

						  </div>
						</div>

					</div>

				<% end %>

			</div>

	  </div>
	</div>
</div>